(source "gnu")
(source "melpa")

(package "ts-fold" "0.1.0" "Code folding using tree-sitter")

(package-file "ts-fold.el")
(files "*.el")

(depends-on "emacs" "26.1")
(depends-on "tree-sitter")
(depends-on "s")
(depends-on "fringe-helper")

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
